package com.hamidat.nullpointersapp.utils.firebaseUtils;

import com.google.firebase.firestore.DocumentSnapshot;
import com.google.firebase.firestore.FirebaseFirestore;
import com.google.firebase.firestore.QueryDocumentSnapshot;
import com.google.firebase.firestore.QuerySnapshot;

import java.util.HashMap;
import java.util.Map;

/**
 * FirestoreUsers handles user-related Firestore operations.
 */
public class FirestoreUsers {
    private static final String USERS_COLLECTION = "users";
    private FirebaseFirestore firestore;

    public FirestoreUsers(FirebaseFirestore firestore) {
        this.firestore = firestore;
    }

    /**
     * Adds a new user with the provided userID and username.
     */
    public void addUser(String userID, String userName, FirestoreHelper.FirestoreCallback callback) {
        Map<String, Object> userFields = new HashMap<>();
        userFields.put("username", userName);

        firestore.collection(USERS_COLLECTION)
                .document(userID)
                .set(userFields)
                .addOnSuccessListener(aVoid -> callback.onSuccess("User added successfully!"))
                .addOnFailureListener(callback::onFailure);
    }

    /**
     * Retrieves user information by userID.
     */
    public void getUser(String userID, FirestoreHelper.FirestoreCallback callback) {
        firestore.collection(USERS_COLLECTION)
                .document(userID)
                .get()
                .addOnSuccessListener(documentSnapshot -> {
                    if (documentSnapshot.exists()) {
                        callback.onSuccess(documentSnapshot.getData());
                    } else {
                        callback.onFailure(new Exception("User not found"));
                    }
                })
                .addOnFailureListener(callback::onFailure);
    }

    /**
     * Retrieves user information by username.
     */
    public void getUserByUsername(String username, FirestoreHelper.FirestoreCallback callback) {
        firestore.collection(USERS_COLLECTION)
                .whereEqualTo("username", username)
                .get()
                .addOnSuccessListener(querySnapshot -> {
                    if (querySnapshot.isEmpty()) {
                        callback.onFailure(new Exception("User not found"));
                    } else {
                        // Assume username is unique and return the first match.
                        DocumentSnapshot doc = querySnapshot.getDocuments().get(0);
                        Map<String, Object> userData = doc.getData();
                        // Include autogenerated UID in the result.
                        userData.put("userId", doc.getId());
                        callback.onSuccess(userData);
                    }
                })
                .addOnFailureListener(callback::onFailure);
    }
}
